### ISSUE TITLE
modeling power flow on disabled buses 

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsMLD.jl#25]
I've been looking through MLD to try and understand how the bus on/off constraints are used.  The code uses a `z_voltage` indicator to set bus voltage, but is this supposed to implicitly turn off the bus? Does it represent a bus being shorted to ground?  What is this supposed to represent in the model?  Is it representative of a damaged bus or does it help with network feasibility by expanding the allowed voltage ranges?

The code includes:

```
    variable_bus_voltage_indicator(pm, relax=true)
    variable_bus_voltage_on_off(pm)
```

To create a  `z_voltage` variable to control whether the voltage on a bus should be set to zero. relaxed, is allows the voltage to vary from 0% to 100%.

```     
constraint_bus_voltage_on_off(pm)
```
Sets the voltage using these variables.

Branch power flow is controlled  by:
```
 _PMs.constraint_ohms_yt_from(pm, i)
 _PMs.constraint_ohms_yt_to(pm, i)
```
using the voltage value and branch conductance/sustenance.  However, I don't see how having one end of a branch at `v=0` prevents power flow into the branch.  Doesn't it act as a ground?

**Comment by ccoffrin** [comment]
The variable `z_voltage` is a 0/1 variable with the semantics, if 0 the bus voltage should be zero (i.e. `vm=0.0, va=0.0`); if 1 bus voltage magnitude should be within the specified bounds (e.g. `0.9^2 <= vm <= 1.1^2`).

In an ideal situation, this is always a discrete variable.  In some MLD formulations it is relaxed and then rounded as a heuristic to increase solver reliability and scalability. 

In the case of `z_voltage==0` the status of all connecting components should also be zero.  This is implied by the MLD objective function, but it should be added as a constraint to support other objective functions.

Off the top of my head, I think we can rename `z_voltage` to `z_bus` and change the semantics to 0/1 if the bus is energized or not.

**Comment by noahrhodes** [comment]
I agree about the implication of `z_voltage==0` meaning connected components should have status=0 and a constraint should be added.  However, only damaged components have a status variable.  Should status variables exist for all devices?   Otherwise, should we use the information about connected components to enforce limits? e.g.
```
for gen_id at bus
     pg <= pg_max * bus_status
     pg >= pg_min * bus_status
end
```

This works for storage, load, and generation, but I don't think it works for the branch flow. 

I think the key concept here is whether a damaged bus implies that each attached item was damaged.  In this case, we can enforce an order on the repairs that the bus must be repaired first.  Everything works.  This does mean there are many more damaged items in the network.

**Comment by ccoffrin** [comment]
See PowerModelsRestoration for a more detailed discussion.  For now in this case, I would just throw an error during model creation and resolve the issue in a data pre-processing step.  Have a look at `propagate_topology_status!` to see what this would look like.  PowerModelsRestoration needs something analogous, like `propagate_damage_status!`.
